version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: c9s
    main: ./cmd/c9s
    binary: c9s
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X c9s/pkg/version.Version={{.Version}}
      - -X c9s/pkg/version.Commit={{.Commit}}
      - -X c9s/pkg/version.Date={{.Date}}

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
